-- Run this script in your Supabase SQL Editor to set up the products table and sample data

-- 1. Create the products table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  price numeric not null,
  image_url text
);

-- 2. Enable Row Level Security (RLS) - Optional but recommended
alter table public.products enable row level security;

-- 3. Create a policy to allow public read access
create policy "Allow public read access"
on public.products
for select
to public
using (true);

-- 4. Create a policy to allow public insert access (for the Add Product form)
create policy "Allow public insert access"
on public.products
for insert
to public
with check (true);

-- 5. Insert sample data
insert into public.products (title, description, price, image_url)
values
  ('Vintage Camera', 'A classic film camera in great condition.', 120.00, 'https://via.placeholder.com/300x200?text=Camera'),
  ('Leather Jacket', 'Genuine leather jacket, size M.', 85.50, 'https://via.placeholder.com/300x200?text=Jacket'),
  ('Wooden Chair', 'Handcrafted oak chair.', 45.00, 'https://via.placeholder.com/300x200?text=Chair');
